version: '3.1'

services:

  postgres:
    image: postgres:12
    restart: always
    ports:
    - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - /Users/rodionov/Documents/ldMayakBot/Postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  phppgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    ports:
      - "8080:80"

networks:
  postgres-compose-network:
    driver: bridge
