version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASS}
    volumes:
      -  /opt/tsn/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  phppgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    depends_on:
      - postgres
    networks:
      - postgres-compose-network


networks:
  postgres-compose-network:
    driver: bridge
