version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
    - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASS}
    volumes:
      -  /opt/tsn/postgres:/var/lib/postgresql/data
    networks:
      - prod-bot-network
networks:
  prod-bot-network:
    driver: bridge
